export const disciplines:string[] = [
    "Maths",
    "Bulgarian language",
    "English language",
    "German language",
    "French language",
    "Spanish language",
    "Russian language",
    "History",
    "Geography",
    "Biology",
    "Chemistry",
    "Physics",
    "Information Technology",
    "Programming",
    "Philosophy",
    "Psychology",
    "Music",
    "Singing",
    "Piano",
    "Guitar",
    "Violin",
    "Arts",
    "Graphic Design",
    "Photography",
    "Physical Education",
    "Chess",
    "Economics",
    "Entrepreneurship",
    "Accounting",
    "Finance",
    "Law",
    "Acting",
    "Dancing",
    "Speech and Debate",
    "SAT/IELTS/TOEFL Preparation"
];
export const provinces:string[] = [
    "Blagoevgrad",
    "Burgas",
    "Varna",
    "Veliko Tarnovo",
    "Vidin",
    "Vratsa",
    "Gabrovo",
    "Dobrich",
    "Kardzhali",
    "Kyustendil",
    "Lovech",
    "Montana",
    "Pazardzhik",
    "Pernik",
    "Pleven",
    "Plovdiv",
    "Razgrad",
    "Ruse",
    "Silistra",
    "Sliven",
    "Smolyan",
    "Sofia",
    "Sofia City",
    "Stara Zagora",
    "Targovishte",
    "Haskovo",
    "Shumen",
    "Yambol"
];
